defaults: &defaults
  facebook:
    api_key: "151504752339035"
    api_secret: "aad36e348128f5d8a2075d80de1b07a6"
    redirect_uri: 'https://localhost:3001/users/auth/facebook/callback'
  google:
    api_key: '300931973233-n0shqkm5e9ifi2scbc1v3k4tb7p9kaoh.apps.googleusercontent.com'
    api_secret: 'Y88rPvi0DmAItiJSbEQ1pZXi'
    redirect_uri: 'http://localhost:3000/users/auth/google_oauth2/callback'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  facebook:
    api_key: "713749919016164"
    api_secret: "2c140244eac02d6aff6315fd3147916c"
    redirect_uri: 'https://starhotel.herokuapp.com/users/auth/facebook/callback  '
  google:
    api_key: "300931973233-mttg01r2o0sjtaepgcdhlnve7k54mf35.apps.googleusercontent.com"
    api_secret: "Ks7ppZs5IFmO51tMFFwEy5Om"
    redirect_uri: 'https://starhotel.herokuapp.com/users/auth/google_oauth2/callback'